// <auto-generated />
using System;
using Kanbada.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kanbada.Api.Persistence.Migrations
{
    [DbContext(typeof(KanbadaDbContext))]
    [Migration("20260929132934_GitHubProjectsSynchronization")]
    partial class GitHubProjectsSynchronization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kanbada.Api.ActivityEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "Position");

                    b.ToTable("workspace_activity", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.BucketEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("buckets", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardAssigneeEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("text")
                        .HasColumnName("member_email");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "MemberEmail");

                    b.HasIndex("WorkspaceId", "MemberEmail");

                    b.ToTable("card_assignees", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardAttachmentEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "FileId");

                    b.HasIndex("WorkspaceId", "FileId");

                    b.ToTable("card_attachments", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardCommentEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "CardId", "Position");

                    b.ToTable("card_comments", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BucketId")
                        .HasColumnType("text")
                        .HasColumnName("bucket_id");

                    b.Property<string>("Cover")
                        .HasColumnType("text")
                        .HasColumnName("cover");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("Due")
                        .HasColumnType("date")
                        .HasColumnName("due");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_id");

                    b.Property<string>("SwimlaneId")
                        .HasColumnType("text")
                        .HasColumnName("swimlane_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "BucketId");

                    b.HasIndex("WorkspaceId", "Due");

                    b.HasIndex("WorkspaceId", "StatusId");

                    b.HasIndex("WorkspaceId", "Position", "Id");

                    b.HasIndex("WorkspaceId", "ProjectId", "SwimlaneId");

                    b.HasIndex("WorkspaceId", "ProjectId", "BucketId", "Position", "Id");

                    b.HasIndex("WorkspaceId", "ProjectId", "StatusId", "Position", "Id");

                    b.ToTable("cards", null, t =>
                        {
                            t.HasCheckConstraint("cards_priority", "priority IN ('Low','Medium','High')");

                            t.HasCheckConstraint("cards_uppercase_id", "id ~ '^KB-[A-Z0-9-]+$'");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.CardLabelEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("LabelId")
                        .HasColumnType("text")
                        .HasColumnName("label_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "LabelId");

                    b.HasIndex("WorkspaceId", "LabelId");

                    b.ToTable("card_labels", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ChecklistItemEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "CardId", "Position");

                    b.ToTable("checklist_items", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ExportChunkEntity", b =>
                {
                    b.Property<Guid>("ExportId")
                        .HasColumnType("uuid")
                        .HasColumnName("export_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.HasKey("ExportId", "Position");

                    b.ToTable("export_chunks", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ExportJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Processed")
                        .HasColumnType("integer")
                        .HasColumnName("processed");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<long?>("SnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_version");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("WorkspaceId", "UserId", "CreatedAt", "Id");

                    b.ToTable("exports", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.GitHubApprovedHostEntity", b =>
                {
                    b.Property<string>("Authority")
                        .HasColumnType("text")
                        .HasColumnName("authority");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.HasKey("Authority");

                    b.ToTable("github_approved_hosts", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.GitHubConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("DueFieldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("due_field_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_finished_at");

                    b.Property<DateTimeOffset?>("LastStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_started_at");

                    b.Property<int>("LastSyncedCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_synced_count");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_type");

                    b.Property<string>("PriorityFieldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority_field_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("integer")
                        .HasColumnName("project_number");

                    b.Property<string>("ProtectedToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protected_token");

                    b.Property<string>("RemoteProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_project_id");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<DateTimeOffset?>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("StatusFieldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_field_id");

                    b.Property<bool>("SyncAssignees")
                        .HasColumnType("boolean")
                        .HasColumnName("sync_assignees");

                    b.Property<bool>("SyncLabels")
                        .HasColumnType("boolean")
                        .HasColumnName("sync_labels");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "NextRunAt");

                    b.HasIndex("WorkspaceId", "ProjectId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "BaseUrl", "RemoteProjectId")
                        .IsUnique();

                    b.ToTable("github_connections", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.GitHubLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("ContentId")
                        .HasColumnType("text")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<bool>("CreationPending")
                        .HasColumnType("boolean")
                        .HasColumnName("creation_pending");

                    b.Property<string>("DisplayKey")
                        .HasColumnType("text")
                        .HasColumnName("display_key");

                    b.Property<string>("GitHubHash")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_hash");

                    b.Property<bool>("Initialized")
                        .HasColumnType("boolean")
                        .HasColumnName("initialized");

                    b.Property<string>("ItemId")
                        .HasColumnType("text")
                        .HasColumnName("item_id");

                    b.Property<string>("KanbadaHash")
                        .HasColumnType("text")
                        .HasColumnName("kanbada_hash");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<Guid?>("SeenRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("seen_run_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<bool>("WritePending")
                        .HasColumnType("boolean")
                        .HasColumnName("write_pending");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "CardId")
                        .IsUnique();

                    b.HasIndex("ConnectionId", "ContentId")
                        .IsUnique();

                    b.HasIndex("ConnectionId", "ItemId")
                        .IsUnique();

                    b.ToTable("github_links", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.GitHubMappingEntity", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("GitHubValue")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_value");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("KanbadaValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kanbada_value");

                    b.HasKey("ConnectionId", "Kind", "GitHubValue");

                    b.ToTable("github_mappings", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.HistoryChangeEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("HistoryId")
                        .HasColumnType("text")
                        .HasColumnName("history_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "CardId", "HistoryId", "Position");

                    b.ToTable("history_changes", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.HistoryEntryEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "Id");

                    b.ToTable("card_history", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.IdentityEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "Subject");

                    b.HasIndex("UserId");

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.JiraApprovedHostEntity", b =>
                {
                    b.Property<string>("Authority")
                        .HasColumnType("text")
                        .HasColumnName("authority");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.HasKey("Authority");

                    b.ToTable("jira_approved_hosts", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.JiraConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edition");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("IssueTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issue_type_id");

                    b.Property<string>("JiraProjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jira_project_key");

                    b.Property<string>("Jql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jql");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_finished_at");

                    b.Property<DateTimeOffset?>("LastStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_started_at");

                    b.Property<int>("LastSyncedCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_synced_count");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<string>("ProtectedToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protected_token");

                    b.Property<DateTimeOffset?>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<bool>("SyncAssignees")
                        .HasColumnType("boolean")
                        .HasColumnName("sync_assignees");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "NextRunAt");

                    b.HasIndex("WorkspaceId", "ProjectId")
                        .IsUnique();

                    b.ToTable("jira_connections", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.JiraLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<bool>("CreationPending")
                        .HasColumnType("boolean")
                        .HasColumnName("creation_pending");

                    b.Property<string>("JiraHash")
                        .HasColumnType("text")
                        .HasColumnName("jira_hash");

                    b.Property<string>("JiraIssueId")
                        .HasColumnType("text")
                        .HasColumnName("jira_issue_id");

                    b.Property<string>("JiraKey")
                        .HasColumnType("text")
                        .HasColumnName("jira_key");

                    b.Property<string>("KanbadaHash")
                        .HasColumnType("text")
                        .HasColumnName("kanbada_hash");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "CardId")
                        .IsUnique();

                    b.HasIndex("ConnectionId", "JiraIssueId")
                        .IsUnique();

                    b.ToTable("jira_links", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.JiraMappingEntity", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("JiraValue")
                        .HasColumnType("text")
                        .HasColumnName("jira_value");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("KanbadaValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kanbada_value");

                    b.HasKey("ConnectionId", "Kind", "JiraValue");

                    b.ToTable("jira_mappings", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.LabelEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name")
                        .HasComputedColumnSql("lower(btrim(name))", true);

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("labels_workspace_normalized_name");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.MemberEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initials");

                    b.Property<string>("InviteToken")
                        .HasColumnType("text")
                        .HasColumnName("invite_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("WorkspaceId", "Email");

                    b.HasIndex("InviteToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("members_normalized_email", "email = lower(email)");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.NotificationEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("At")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.HasKey("WorkspaceId", "Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("notifications_assignment_recipient", "(recipient_id IS NULL) = (card_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.PlatformBrandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accent");

                    b.Property<string>("CollapsedLogo")
                        .HasColumnType("text")
                        .HasColumnName("collapsed_logo");

                    b.Property<int>("CornerRadius")
                        .HasColumnType("integer")
                        .HasColumnName("corner_radius");

                    b.Property<string>("DarkBackground")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dark_background");

                    b.Property<string>("DarkBorder")
                        .HasColumnType("text")
                        .HasColumnName("dark_border");

                    b.Property<string>("DarkSurface")
                        .HasColumnType("text")
                        .HasColumnName("dark_surface");

                    b.Property<string>("DarkText")
                        .HasColumnType("text")
                        .HasColumnName("dark_text");

                    b.Property<string>("DefaultTheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_theme");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("font_family");

                    b.Property<int>("FontScale")
                        .HasColumnType("integer")
                        .HasColumnName("font_scale");

                    b.Property<string>("LightBackground")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("light_background");

                    b.Property<string>("LightBorder")
                        .HasColumnType("text")
                        .HasColumnName("light_border");

                    b.Property<string>("LightSurface")
                        .HasColumnType("text")
                        .HasColumnName("light_surface");

                    b.Property<string>("LightText")
                        .HasColumnType("text")
                        .HasColumnName("light_text");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary");

                    b.Property<bool>("ShowName")
                        .HasColumnType("boolean")
                        .HasColumnName("show_name");

                    b.Property<string>("SidebarBackground")
                        .HasColumnType("text")
                        .HasColumnName("sidebar_background");

                    b.Property<string>("SidebarText")
                        .HasColumnType("text")
                        .HasColumnName("sidebar_text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("platform_branding", null, t =>
                        {
                            t.HasCheckConstraint("platform_branding_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.ProjectEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("System")
                        .HasColumnType("text")
                        .HasColumnName("system");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.RecoveryCodeEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.HasKey("UserId", "Hash");

                    b.ToTable("recovery_codes", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("TwoFactorVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_verified");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ShareEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Token");

                    b.HasIndex("CreatorId");

                    b.HasIndex("WorkspaceId", "CardId")
                        .IsUnique();

                    b.ToTable("shares", null, t =>
                        {
                            t.HasCheckConstraint("shares_access", "access IN ('signed-in','members')");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.StatusEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.SwimlaneEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("swimlanes", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<bool>("PhotoRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("photo_required");

                    b.Property<int>("TwoFactorFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("two_factor_failed_attempts");

                    b.Property<long?>("TwoFactorLastStep")
                        .HasColumnType("bigint")
                        .HasColumnName("two_factor_last_step");

                    b.Property<DateTimeOffset?>("TwoFactorLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("two_factor_locked_until");

                    b.Property<DateTimeOffset?>("TwoFactorPendingExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("two_factor_pending_expires_at");

                    b.Property<string>("TwoFactorPendingSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_pending_secret");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_secret");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("password_hash IS NOT NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_normalized_email", "email = lower(email)");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.WorkspaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Banner")
                        .HasColumnType("text")
                        .HasColumnName("banner");

                    b.Property<double?>("BannerPosition")
                        .HasColumnType("double precision")
                        .HasColumnName("banner_position");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<bool>("Personal")
                        .HasColumnType("boolean")
                        .HasColumnName("personal");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("personal");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ActivityEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.BucketEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardAssigneeEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.MemberEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "MemberEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardAttachmentEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.FileEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "FileId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardCommentEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.BucketEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "BucketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kanbada.Api.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.StatusEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.SwimlaneEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId", "SwimlaneId")
                        .HasPrincipalKey("WorkspaceId", "ProjectId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kanbada.Api.CardLabelEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.LabelEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ChecklistItemEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ExportChunkEntity", b =>
                {
                    b.HasOne("Kanbada.Api.ExportJobEntity", null)
                        .WithMany()
                        .HasForeignKey("ExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ExportJobEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.FileEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.GitHubConnectionEntity", b =>
                {
                    b.HasOne("Kanbada.Api.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.GitHubLinkEntity", b =>
                {
                    b.HasOne("Kanbada.Api.GitHubConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.GitHubMappingEntity", b =>
                {
                    b.HasOne("Kanbada.Api.GitHubConnectionEntity", null)
                        .WithMany("Mappings")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.HistoryChangeEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.HistoryEntryEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId", "HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.HistoryEntryEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.IdentityEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.JiraConnectionEntity", b =>
                {
                    b.HasOne("Kanbada.Api.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.JiraLinkEntity", b =>
                {
                    b.HasOne("Kanbada.Api.JiraConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.JiraMappingEntity", b =>
                {
                    b.HasOne("Kanbada.Api.JiraConnectionEntity", null)
                        .WithMany("Mappings")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.LabelEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.MemberEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.NotificationEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ProjectEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.RecoveryCodeEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.SessionEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ShareEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.StatusEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.SwimlaneEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.WorkspaceEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.GitHubConnectionEntity", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("Kanbada.Api.JiraConnectionEntity", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
