// <auto-generated />
using System;
using Kanbada.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kanbada.Api.Persistence.Migrations
{
    [DbContext(typeof(KanbadaDbContext))]
    partial class KanbadaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kanbada.Api.ActivityEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "Position");

                    b.ToTable("workspace_activity", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.BucketEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("buckets", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardAssigneeEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("text")
                        .HasColumnName("member_email");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "MemberEmail");

                    b.HasIndex("WorkspaceId", "MemberEmail");

                    b.ToTable("card_assignees", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardAttachmentEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "FileId");

                    b.HasIndex("WorkspaceId", "FileId");

                    b.ToTable("card_attachments", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardCommentEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "CardId", "Position");

                    b.ToTable("card_comments", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.CardEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BucketId")
                        .HasColumnType("text")
                        .HasColumnName("bucket_id");

                    b.Property<string>("Cover")
                        .HasColumnType("text")
                        .HasColumnName("cover");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("Due")
                        .HasColumnType("date")
                        .HasColumnName("due");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_id");

                    b.Property<string>("SwimlaneId")
                        .HasColumnType("text")
                        .HasColumnName("swimlane_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "BucketId");

                    b.HasIndex("WorkspaceId", "Due");

                    b.HasIndex("WorkspaceId", "StatusId");

                    b.HasIndex("WorkspaceId", "ProjectId", "SwimlaneId");

                    b.ToTable("cards", null, t =>
                        {
                            t.HasCheckConstraint("cards_priority", "priority IN ('Low','Medium','High')");

                            t.HasCheckConstraint("cards_uppercase_id", "id ~ '^KB-[A-Z0-9-]+$'");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.CardLabelEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("LabelId")
                        .HasColumnType("text")
                        .HasColumnName("label_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "LabelId");

                    b.HasIndex("WorkspaceId", "LabelId");

                    b.ToTable("card_labels", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ChecklistItemEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "CardId", "Position");

                    b.ToTable("checklist_items", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.HistoryChangeEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("HistoryId")
                        .HasColumnType("text")
                        .HasColumnName("history_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WorkspaceId", "CardId", "HistoryId", "Position");

                    b.ToTable("history_changes", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.HistoryEntryEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "CardId", "Id");

                    b.ToTable("card_history", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.IdentityEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "Subject");

                    b.HasIndex("UserId");

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.LabelEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.MemberEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initials");

                    b.Property<string>("InviteToken")
                        .HasColumnType("text")
                        .HasColumnName("invite_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("WorkspaceId", "Email");

                    b.HasIndex("InviteToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("members_normalized_email", "email = lower(email)");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.NotificationEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("At")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ProjectEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("System")
                        .HasColumnType("text")
                        .HasColumnName("system");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ShareEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Token");

                    b.HasIndex("CreatorId");

                    b.HasIndex("WorkspaceId", "CardId")
                        .IsUnique();

                    b.ToTable("shares", null, t =>
                        {
                            t.HasCheckConstraint("shares_access", "access IN ('signed-in','members')");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.StatusEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.SwimlaneEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("swimlanes", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("password_hash IS NOT NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_normalized_email", "email = lower(email)");
                        });
                });

            modelBuilder.Entity("Kanbada.Api.WorkspaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Banner")
                        .HasColumnType("text")
                        .HasColumnName("banner");

                    b.Property<double?>("BannerPosition")
                        .HasColumnType("double precision")
                        .HasColumnName("banner_position");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<bool>("Personal")
                        .HasColumnType("boolean")
                        .HasColumnName("personal");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("personal");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Kanbada.Api.ActivityEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.BucketEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardAssigneeEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.MemberEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "MemberEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardAttachmentEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.FileEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "FileId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardCommentEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.CardEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.BucketEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "BucketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kanbada.Api.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.StatusEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.SwimlaneEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId", "SwimlaneId")
                        .HasPrincipalKey("WorkspaceId", "ProjectId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kanbada.Api.CardLabelEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.LabelEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ChecklistItemEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.FileEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.HistoryChangeEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.HistoryEntryEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId", "HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.HistoryEntryEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.IdentityEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.LabelEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.MemberEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.NotificationEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ProjectEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.SessionEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.ShareEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.StatusEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.SwimlaneEntity", b =>
                {
                    b.HasOne("Kanbada.Api.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanbada.Api.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanbada.Api.WorkspaceEntity", b =>
                {
                    b.HasOne("Kanbada.Api.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
