using System.Text.Json.Nodes;

namespace Kanbada.Api;

public sealed record ApiOperationExample(
    string Method, string Path, string Summary, string Description, string ExampleUrl,
    string SuccessCode = "200", JsonNode? Request = null, JsonNode? Response = null,
    string ResponseType = "application/json");

/// <summary>Human-readable examples kept separate from route execution. Coverage is enforced by tests.</summary>
public static class ApiOperationCatalog
{
    private const string Workspace = "/api/workspaces/studio";
    private const string Card = Workspace + "/cards/" + ApiExamples.CardId;
    private const string Share = "/api/shares/" + ApiExamples.Token;
    private const string Invitation = "/api/invitations/" + ApiExamples.Token;

    public static IReadOnlyList<ApiOperationExample> Operations { get; } =
    [
        new("GET", "/api/health", "Check API/database connectivity",
            "Public connectivity probe. Returns 200 when a database connection opens; an unexpected database connection failure returns 500. Use readiness for orchestration.",
            "/api/health", Response: ApiExamples.Json(new { status = "healthy", database = "PostgreSQL" })),
        new("GET", "/api/health/ready", "Check readiness",
            "Public ASP.NET Core health-check service. Returns plain-text Healthy with 200, or Unhealthy with 503 when PostgreSQL is unavailable.",
            "/api/health/ready", Response: JsonValue.Create("Healthy"), ResponseType: "text/plain"),
        new("GET", "/api/auth/session", "Read the current session and provider availability",
            "Public. Returns user=null when signed out; this is not an error. Provider booleans indicate whether client credentials are configured. twoFactorSetupRequired and twoFactorVerificationRequired identify restricted sessions; the portal gates workspace access accordingly. The example shows an authenticated account.",
            "/api/auth/session", Response: ApiExamples.Json(new { user = new { id = ApiExamples.UserId, name = "Alex Morgan", email = "alex@example.test", provider = "email" }, providers = new { google = false, microsoft = false } })),
        new("POST", "/api/auth/register", "Create an email account and sign in",
            "Public, rate limited. Requires a valid email, a 1–120 character display name, and a 12–200 character password. Creates My Workspace and My activities and issues a restricted HttpOnly setup-session cookie. All new accounts must complete authenticator enrollment before accessing workspace APIs; twoFactorSetupRequired=true is returned. Duplicate password-account emails return 409. Example credentials are fictional: replace them before sending.",
            "/api/auth/register", Request: ApiExamples.Json(new { email = "alex@example.test", password = "Replace-this-example-password!", name = "Alex Morgan" }), Response: ApiExamples.Json(new { id = ApiExamples.UserId, twoFactorSetupRequired = true })),
        new("POST", "/api/auth/login", "Sign in with an email and password",
            "Public, rate limited. Valid credentials without a required second factor establish an eight-hour cookie session (204). If 2FA is enabled and code is omitted, returns 200 with twoFactorRequired=true and no session. Resubmit email/password with code (authenticator or recovery code). Invalid/replayed codes return 400; account lockout returns 429. Incorrect credentials return 401. Execute this on the same origin as Scalar; subsequent browser requests use the cookie. An empty name is accepted because it is not used during login.",
            "/api/auth/login", "204", Request: ApiExamples.Json(new { email = "alex@example.test", password = "Replace-this-example-password!", name = "" })),
        new("GET", "/api/auth/two-factor", "Read authenticator status",
            "Requires a session. Reports enabled status, required policy, whether password confirmation is needed, and remaining recovery-code count. Never returns secrets or recovery codes.",
            "/api/auth/two-factor", Response: ApiExamples.Json(new { available = true, enabled = false, recoveryCodesRemaining = 0, required = true, passwordRequired = true })),
        new("POST", "/api/auth/two-factor/setup", "Start authenticator setup",
            "Requires a session and current password for password accounts (external identities send an empty password). Returns a private setup key and otpauth URI to render locally as a QR code. Pending setup expires after ten minutes and does not enable 2FA. Restarting replaces pending setup; enabled accounts return 409. Do not log or share this response.",
            "/api/auth/two-factor/setup", Request: ApiExamples.Json(new { password = "Replace-this-example-password!" }), Response: ApiExamples.Json(new { secret = "EXAMPLE-ONLY", uri = "otpauth://totp/Kanbada:alex%40example.test?secret=EXAMPLE-ONLY&issuer=Kanbada&digits=6&period=30" })),
        new("POST", "/api/auth/two-factor/confirm", "Enable authenticator protection",
            "Requires a session, current password, and a valid six-digit code for the unexpired pending setup. Enables 2FA, revokes other sessions, and returns ten single-use recovery codes exactly once. The confirmation code cannot be reused for login. Save recovery codes securely.",
            "/api/auth/two-factor/confirm", Request: ApiExamples.Json(new { password = "Replace-this-example-password!", code = "123456" }), Response: ApiExamples.Json(new { codes = new[] { "EXAMPLE-ONLY-SAVE-REAL-CODES" } })),
        new("POST", "/api/auth/two-factor/recovery-codes", "Replace recovery codes",
            "Requires a session, current password, and an unused authenticator or recovery code. Invalidates all previous recovery codes and revokes other sessions. Returns ten new recovery codes exactly once.",
            "/api/auth/two-factor/recovery-codes", Request: ApiExamples.Json(new { password = "Replace-this-example-password!", code = "123456" }), Response: ApiExamples.Json(new { codes = new[] { "EXAMPLE-ONLY-SAVE-REAL-CODES" } })),
        new("POST", "/api/auth/two-factor/verify", "Complete second-factor sign-in",
            "Requires a restricted session obtained through external sign-in or an existing session requiring second-factor verification. Accepts an unused authenticator or recovery code and upgrades only the current session. No workspace access is permitted beforehand.",
            "/api/auth/two-factor/verify", "204", Request: ApiExamples.Json(new { password = "", code = "123456" })),
        new("POST", "/api/auth/two-factor/disable", "Disable authenticator protection",
            "Requires a session, current password, and an unused authenticator or recovery code. Returns 403 for accounts subject to mandatory 2FA. For legacy optional accounts, removes authenticator secrets and recovery codes and revokes other sessions. Five failed verification attempts lock changes and second-factor verification for five minutes.",
            "/api/auth/two-factor/disable", "204", Request: ApiExamples.Json(new { password = "Replace-this-example-password!", code = "123456" })),
        new("POST", "/api/auth/logout", "Revoke the current session",
            "No JSON body. Deletes the current server session and expires its cookie. Also succeeds when already signed out. Reusing the revoked session returns 401 on protected endpoints.",
            "/api/auth/logout", "204"),
        new("GET", "/api/auth/{provider}/start", "Start Google or Microsoft sign-in",
            "Public, rate limited. Open this URL as browser navigation, not an AJAX request. Provider must be google or microsoft. Redirects to that provider; returns 503 if credentials are not configured. returnUrl must be a local path; unsafe values fall back to /. The cookie middleware owns the provider callback route.",
            "/api/auth/google/start?returnUrl=%2F", "302", ResponseType: ""),
        new("GET", "/api/auth/complete", "Complete external sign-in",
            "Internal browser redirect target after provider middleware has authenticated the temporary external cookie. Do not call directly to sign in: missing external authentication returns 401. Issues a restricted session and redirects to a validated local returnUrl. Newly created external identities must enroll an authenticator; returning enrolled identities must verify an authenticator/recovery code before workspace access.",
            "/api/auth/complete?provider=google&returnUrl=%2F", "302", ResponseType: ""),
        new("GET", "/api/workspaces", "List your workspaces",
            "Requires a session. Returns only current memberships, with the caller's personal workspace first. The owner sees their personal UUID as the alias studio. canManage indicates owner-only management capability.",
            "/api/workspaces", Response: ApiExamples.Json(new[] { new { id = "studio", name = "My Workspace", personal = true, canManage = true } })),
        new("POST", "/api/workspaces", "Create a workspace",
            "Requires a session. Name must be 1–80 characters and unique among the caller's workspace names. Creates owner membership, default statuses, and the protected My activities project. Duplicate names return 409.",
            "/api/workspaces", Request: ApiExamples.Json(new { name = "Product delivery" }), Response: ApiExamples.CreatedWorkspace()),
        new("GET", "/api/workspaces/{id}", "Read a complete workspace snapshot",
            "Requires membership. Returns all collections, current version, ETag, and server-derived management/member fields. Inaccessible workspaces return 404. Keep the version for PATCH. Send If-None-Match with the quoted ETag for subsequent refreshes: an unchanged authorized workspace returns 304 with no body.",
            Workspace, Response: ApiExamples.Workspace()),
        new("PATCH", "/api/workspaces/{id}", "Apply only changed workspace fields",
            "Requires membership and If-Match from the loaded workspace. Send a changes array of add, remove, or replace operations with JSON Pointer paths. Array indexes refer to that exact version and operations run in order. This supports atomic card edits, card creation/removal, definitions, projects, members, images, activity, and notifications without resending unrelated data. History, identity, version, and permission fields are server-controlled. Paths must target workspace collections or editable workspace settings; whole-document replacement is forbidden. Maximum 10000 operations. Returns only canonical changes relative to the original loaded state, including generated history and the new version. Apply those changes locally in order; no full reload is necessary. Validation/authorization is identical to PUT. Stale=409, missing If-Match=428, malformed changes=400; failures persist nothing.",
            Workspace, Request: ApiExamples.Json(new { changes = new[] { new { op = "replace", path = "/tasks/0/title", value = "Updated card title" } } }),
            Response: ApiExamples.Json(new { version = 2, changes = new object[] { new { op = "replace", path = "/tasks/0/title", value = "Updated card title" }, new { op = "replace", path = "/version", value = 2 } } })),
        new("PUT", "/api/workspaces/{id}", "Replace a workspace snapshot (compatibility)",
            "Compatibility endpoint; the portal uses compact PATCH requests instead. Requires membership and If-Match containing the last-read version. GET your own snapshot first, change its fields, then PUT it. The example illustrates a complete card with labels, bucket, swimlane, assignee, comment, checklist, and no due date; its sample identities must not replace your real owner/member fields. Missing version returns 428; stale version returns 409 with no changes. Do not blindly retry. Owner-only changes include membership and workspace settings. My activities and My Workspace are protected. History, membership IDs, ownership, and version are server-controlled. Saves synchronize card references and delete unreferenced saved attachments/shares.",
            Workspace, Request: ApiExamples.Workspace(), Response: ApiExamples.SavedWorkspace()),
        new("DELETE", "/api/workspaces/{id}", "Delete a workspace permanently",
            "Owner only. No JSON body. Deletes its cards, files, memberships, and sharing links. Personal workspaces cannot be deleted (400); non-owners receive 403. Use a real non-personal workspace UUID, never studio. Inaccessible/missing workspaces return 404.",
            "/api/workspaces/" + ApiExamples.WorkspaceId, "204"),
        new("GET", "/api/workspaces/{id}/export", "Download workspace JSON",
            "Requires membership. Returns the complete workspace as application/json with Content-Disposition attachment; filename workspace.json. This is a JSON export, not the dashboard PDF, which is generated in the portal.",
            Workspace + "/export", Response: ApiExamples.Workspace()),
        new("GET", "/api/workspaces/{id}/{collection}", "Read a workspace collection",
            "Requires membership. Collection is projects, tasks, members, statuses, buckets, labels, swimlanes, notifications, or activity. Returns the complete array, without pagination. Unknown collections return 404. The default example reads tasks.",
            Workspace + "/tasks", Response: new JsonArray(ApiExamples.Card())),
        new("POST", "/api/workspaces/{id}/cards", "Create a card",
            "Requires workspace membership. Only title is required. Defaults: project=my-activities, first workspace status, priority=Medium, blank optional due date, and empty labels/assignees/checklist/comments/attachments. Specify existing project IDs and exact workflow/member names when overriding defaults. The API generates an uppercase KB-... ID and history; clients cannot choose them. Returns 201 with the card, Location pointing to its GET endpoint, and ETag containing the new workspace version. No If-Match is needed for this command; a competing workspace write may return 409. Uploaded attachments must already belong to the workspace. Start with the minimal example below.",
            Workspace + "/cards", "201", Request: ApiExamples.Json(new { title = "Review release requirements" }), Response: ApiExamples.SavedWorkspace()["tasks"]![0]!.DeepClone()),
        new("GET", "/api/workspaces/{id}/cards/{cardId}", "Read a card including its history",
            "Requires workspace membership. Card ID lookup is case-insensitive; saved IDs are uppercase KB-... identifiers. Returns 404 for missing cards or inaccessible workspaces. This ordinary card route is distinct from a token-based read-only share.",
            Card, Response: ApiExamples.SavedWorkspace()["tasks"]![0]!.DeepClone()),
        new("GET", "/api/workspaces/{id}/metrics", "Get filtered live workspace metrics",
            "Requires membership. Omit all query parameters for active projects across the workspace. project is a project ID; bucket and swimlane are exact stored names. Filters combine with AND. Archived projects are excluded; completion follows status.complete; overdue uses the UTC date and excludes blank due dates. Query example: ?project=my-activities&bucket=Discovery&swimlane=Research. Labels are filtered by the portal, not a parameter of this endpoint.",
            Workspace + "/metrics?project=my-activities&bucket=Discovery&swimlane=Research",
            Response: ApiExamples.Json(new { total = 1, completed = 0, open = 1, overdue = 0, highPriority = 1, unassigned = 0 })),
        new("POST", "/api/workspaces/{id}/files", "Upload a card attachment",
            "Requires membership. Send multipart/form-data with a binary file field named file, maximum 25 MiB. Select a real file in Scalar; the example filename is descriptive. Do not manually set Content-Type in browser FormData requests because the browser supplies the boundary. Returns metadata; add it to the card's attachments array through PATCH using If-Match. Unreferenced uploads can be deleted separately.",
            Workspace + "/files", Request: ApiExamples.Json(new { file = "requirements.pdf (select a local binary file)" }), Response: ApiExamples.Attachment()),
        new("GET", "/api/files/{id}", "Download an attachment",
            "Requires membership of the file's workspace. Returns bytes as application/octet-stream with Content-Disposition attachment. The filename comes from stored metadata. Missing/inaccessible files return 404. The response shown is illustrative binary content, not JSON.",
            "/api/files/" + ApiExamples.FileId, Response: JsonValue.Create("<binary requirements.pdf bytes>"), ResponseType: "application/octet-stream"),
        new("DELETE", "/api/files/{id}", "Discard an unreferenced upload",
            "Requires a session. No JSON body. Only deletes uploads owned by the caller and not referenced by saved cards. Idempotent 204 does not imply a referenced file was deleted. Remove saved card references with workspace PUT to trigger transaction-based file cleanup.",
            "/api/files/" + ApiExamples.FileId, "204"),
        new("GET", "/api/workspaces/{id}/cards/{cardId}/share", "Read the current card sharing link",
            "Requires membership. Returns sharing metadata or JSON null if no link exists. An expired link may still be returned as current metadata; resolving it returns 404. Read expiresAt before distributing a link.",
            Card + "/share", Response: ApiExamples.Share()),
        new("POST", "/api/workspaces/{id}/cards/{cardId}/share", "Create or replace a card sharing link",
            "Requires membership and an existing card. access is members or signed-in. days is 0 (no expiry), 7, or 30. signed-in allows any authenticated holder of the token; members also checks workspace membership. Replacing the link immediately invalidates the previous token. Present the returned token as /?share={token}. Links are read-only.",
            Card + "/share", Request: ApiExamples.Json(new { access = "members", days = 7 }), Response: ApiExamples.Share()),
        new("DELETE", "/api/shares/{token}", "Revoke a sharing link",
            "Requires a session and workspace membership for a matching link. No JSON body. Idempotent 204, including when the token does not exist or cannot be revoked by this account. A revoked link can no longer be resolved.",
            Share, "204"),
        new("GET", "/api/shares/{token}", "Read a shared card",
            "Requires authentication even for signed-in access links. members links additionally require membership (403 otherwise). Expired, revoked, or unknown tokens return 404. Returns one card and display context only, without the workspace's full tasks or members arrays. All example tokens are placeholders: use a token returned by the share creation endpoint.",
            Share, Response: ApiExamples.SharedCard()),
        new("GET", "/api/shares/{token}/files/{id}", "Download a file through a card link",
            "Requires the same authentication/access/expiry checks as the shared card. File must be referenced by that exact card. Returns attachment bytes; unrelated/missing files return 404. Use the share token and one of the returned card attachment IDs.",
            Share + "/files/" + ApiExamples.FileId, Response: JsonValue.Create("<binary requirements.pdf bytes>"), ResponseType: "application/octet-stream"),
        new("GET", "/api/invitations/{token}", "Read a pending workspace invitation",
            "Requires authentication and a valid unused invitation token. Returns workspace name and invited email; missing/used invitations return 404. An owner creates pending members through workspace PUT and copies their invitationToken into /?invite={token}; Kanbada does not send email.",
            Invitation, Response: ApiExamples.Json(new { workspace = "Product delivery", email = "colleague@example.test" })),
        new("POST", "/api/invitations/{token}/accept", "Accept a workspace invitation",
            "Requires a session matching the invited email (403 otherwise). No JSON body. Assigns the user to the pending membership, invalidates the invitation token, and increments workspace version. Already-member conflicts return 409; unavailable invitations return 404. Open the returned workspaceId with GET /api/workspaces/{id}.",
            Invitation + "/accept", Response: ApiExamples.Json(new { workspaceId = ApiExamples.WorkspaceId }))
    ];
}
